// Angular_React_Vue/Day3/Assignments/Vue/Source/assignment/src/components/LogIn.vue
<template lang="">
    <div>
       <div class="card p-2 m-5">
    <h1 class="card-header">THIS IS LOGIN PART</h1>
    <label  class="p-2"> Enter Username:</label>
    <input type="text" v-model="name">
    <label  class="p-2"> Enter Password:</label>
    <input type="text" v-model="passWord">
    <button type="button" v-on:click="check()" class="w-25 bg-primary text-white m-2">Submit</button>
    <h3 class="card-footer"> You are {{answer}}</h3>
</div> 
    </div>
</template>
<script>
export default {
    name: "LogIn",
    prop:{
        msg:String
    },
    data() {
        return {
            name:'',
passWord:'',
answer:'',
        }
    },
    check(){
  if(this.name =="admin" && this.passWord =="admin"){
    this.answer="Logged In";
    console.log(this.answer);
  }
  else{
    this.answer="Not logged in"
    console.log(this.answer);
  }
}
}
</script>
<style lang="">
    
</style>

// React/Day3/Assignment/DataBinding/SourceCode/assignment/src/LogIn.js
import React, { useState } from 'react'
const Login=()=>{
    const[userName, setusername]=useState("")
    const[passWord, setpassword]=useState("")
    const [result, setresult] = useState("")
    const Result=()=>{
        if(userName=="admin"&& passWord=="admin"){
            setresult("Logged In");
        }
        else{
            setresult("Not logged in");
        }
    }
return(
    <div class="card">
        <h1 class="card-header">This is Login component</h1>
        <label>Enter Username</label>
        <input type="text" value={userName} onChange={(e)=>setusername(e.target.value)} id="user"></input>
        <label>Enter password</label>
        <input type="text" value={passWord} onChange={(e)=>setpassword(e.target.value)} id="pass"></input>
        <button type="button" onClick = {Result}>Submit</button>
        <div class="card-footer">
            {
                <h4>You are: {result}</h4>
            }
        </div>
    </div>
)}
export default Login
