// Angular_React_Vue/Day3/Assignments/Vue/Source/assignment/src/components/LogIn.vue
<template lang="">
    <div>
       <div class="card p-2 m-5">
    <h1 class="card-header">THIS IS LOGIN PART</h1>
    <label  class="p-2"> Enter Username:</label>
    <input type="text" v-model="name">
    <label  class="p-2"> Enter Password:</label>
    <input type="text" v-model="passWord">
    <button type="button" v-on:click="check()" class="w-25 bg-primary text-white m-2">Submit</button>
    <h3 class="card-footer"> You are {{answer}}</h3>
</div> 
    </div>
</template>
<script>
export default {
    name: "LogIn",
    prop:{
        msg:String
    },
    data() {
        return {
            name:'',
passWord:'',
answer:'',
        }
    },
    check(){
  if(this.name =="admin" && this.passWord =="admin"){
    this.answer="Logged In";
    console.log(this.answer);
  }
  else{
    this.answer="Not logged in"
    console.log(this.answer);
  }
}
}
</script>
<style lang="">
    
</style>

// Angular_React_Vue/Day3/Assignments/Angular/Source/assignment/src/app/log-in/log-in.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-log-in',
  templateUrl: './log-in.component.html',
  styleUrls: ['./log-in.component.css']
})
export class LogInComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
name:any='';
passWord: any= '';
answer:any='';
check(){
  if(this.name =="admin" && this.passWord =="admin"){
    this.answer="Logged In";
    console.log(this.answer);
  }
  else{
    this.answer="Not logged in"
    console.log(this.answer);
  }
}
}

<div class="card p-2 m-5">
    <h4 class="card-header">THIS IS LOGIN PART</h4>
    <label class="p-2"> Enter Username:</label>
    <input type="text" [(ngModel)]="name">
    <label class="p-2"> Enter Password:</label>
    <input type="text" [(ngModel)]="passWord">
    <button type="button" (click)="check()"class="w-25 bg-primary text-white m-2">Submit</button>
    <h3 class="card-footer"> You are: {{answer}}</h3>
</div>
