// Angular_React_Vue/Day3/Assignments/Angular/Source/assignment/src/app/rect-angle/rect-angle.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-rect-angle',
  templateUrl: './rect-angle.component.html',
  styleUrls: ['./rect-angle.component.css']
})
export class RectAngleComponent implements OnInit {
length=0;
breadth=0;
area=0;
  constructor() { }

  ngOnInit(): void {
  }
findArea(){
  this.area= this.length*this.breadth;
}
}

<div class="card p-2 m-5">
<h4 class="card-header">This is the rectangle component</h4>
<label class="p-2">Lenght of the rectangle</label>
<input type="number" [(ngModel)]="length">
<label class="p-2">Breadth of the rectangle</label>
<input type="number" [(ngModel)]="breadth">
<button type="button" (click)="findArea()"class="w-25 bg-primary text-white m-2">Area</button>
<p class="card-footer">The area of rectangle is {{area}}</p>
</div>

// Angular_React_Vue/Day3/Assignments/Vue/Source/assignment/src/components/RectAngle.vue
<template lang="">
    <div class="card p-2 m-5">
        <h1 class="card-header">This is rectangle component</h1>
        <label class="p-2">Lenght of the rectangle</label>
<input type="number" v-model="length">
<label class="p-2">Breadth of the rectangle</label>
<input type="number" v-model="breadth">
<button type="button" v-on:click="findArea()" class="w-25 bg-primary text-white m-2">Area</button>
<p class="card-footer">The area of rectangle is {{area}}</p>
    </div>
</template>
<script>
export default {
    name: "RectAngle",
    props:{
        msg: String
    },
    data(){
        return{
            length:0,
breadth:0,
area:0
        }
},
methods: {
    findArea(){
  this.area= this.length*this.breadth;
}
},
}

</script>
<style lang="">
    
</style>
