// React/Day3/Assignment/DataBinding/SourceCode/assignment/src/SignUp.js
import React, { useState } from 'react'
const SignUp=()=>{
    const[Name, setname]=useState("")
    const[Address, setaddress]=useState("")
    const[PanNumber, setpan]=useState("")
    const [finalname, setfinalname] = useState("")
    const [finaladdress, setfinaladdress] = useState("")
    const [finalpan, setfinalpan] = useState("")
    const Result=()=>{
      setfinalname(Name);
      setfinalpan(PanNumber);
      setfinaladdress(Address);
    }
return(
    <div class="card">
        <h1 class="card-header">This is SignUp component</h1>
        <label>Enter Username</label>
        <input type="text" value={Name} onChange={(e)=>setname(e.target.value)} id="name"></input>
        <label>Enter address</label>
        <input type="text" value={Address} onChange={(e)=>setaddress(e.target.value)} id="address"></input>
        <label>Enter PanNumber</label>
        <input type="text" value={PanNumber} onChange={(e)=>setpan(e.target.value)} id="pan"></input>
        <button type="button" onClick = {Result}>Submit</button>
        <div class="card-footer">
            {
                <div>
               <p>Your name is{finalname}</p>
               <p>Your address is{finaladdress}</p>
               <p>Your pan number is{finalpan}</p>
               </div>
            }
        </div>
    </div>
)}
export default SignUp

// Angular_React_Vue/Day3/Assignments/Vue/Source/assignment/src/components/SignUp.vue
<template>
    <div class="card p-2 m-5">
    <h1 class="card-header">This is signup component</h1>
    <label class="p-2">Name</label>
<input type="text" v-model="Username">
<label class="p-2">Address</label>
<input type="text" v-model="Address">
<label class="p-2">Pan Number</label>
<input type="text" v-model="panNumber">
<button type="button" v-on:click="sign()" class="w-25 bg-primary text-white m-2">Submit</button>
<div class="card-footer">
<p>Your name is: {{Username}}</p>
<p>Your address is: {{Address}}</p>
<p>Your pan number is: {{panNumber}}</p>
<p>{{greeting}}</p>
</div>
    </div>
</template>
<script>
export default {
    name: "SignUp",
    props:{
        msg: String,
    },
    data() {
        return {
         Username:' ',
Address: ' ',
panNumber:' ',   
        }
    },
    methods: {
        sign(){
  var greeting="you are signed in"
}
    },
}
</script>
<style lang="">
    
</style>
