// Angular_React_Vue/Day3/Assignments/Angular/Source/assignment/src/app/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.css']
})
export class SignUpComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
Username: any=' ';
Address:any= ' ';
panNumber: any=' ';
sign(){
  var greeing="you are signed in ";
}
}

<div class="card p-2 m-5">
<h4 class="card-header">This is Sign Up component</h4>
<label class="p-2">Name</label>
<input type="text" [(ngModel)]="Username">
<label class="p-2">Address</label>
<input type="text" [(ngModel)]="Address">
<label class="p-2">Pan Number</label>
<input type="text" [(ngModel)]="panNumber">
<button type="button" (click)="sign()" class="w-25 bg-primary text-white m-2">Submit</button>
<div class="card-footer">
<p>Your name is: {{Username}}</p>
<p>Your address is: {{Address}}</p>
<p>Your pan number is: {{panNumber}}</p>
<p>{{greeting}}</p>
</div>
</div>

// Angular_React_Vue/Day3/Assignments/Vue/Source/assignment/src/components/SignUp.vue
<template>
    <div class="card p-2 m-5">
    <h1 class="card-header">This is signup component</h1>
    <label class="p-2">Name</label>
<input type="text" v-model="Username">
<label class="p-2">Address</label>
<input type="text" v-model="Address">
<label class="p-2">Pan Number</label>
<input type="text" v-model="panNumber">
<button type="button" v-on:click="sign()" class="w-25 bg-primary text-white m-2">Submit</button>
<div class="card-footer">
<p>Your name is: {{Username}}</p>
<p>Your address is: {{Address}}</p>
<p>Your pan number is: {{panNumber}}</p>
<p>{{greeting}}</p>
</div>
    </div>
</template>
<script>
export default {
    name: "SignUp",
    props:{
        msg: String,
    },
    data() {
        return {
         Username:' ',
Address: ' ',
panNumber:' ',   
        }
    },
    methods: {
        sign(){
  var greeting="you are signed in"
}
    },
}
</script>
<style lang="">
    
</style>
