// React/Day4/Assignment/SourceCode/assignment/src/Employee.js
import React, { useState } from 'react'
const Employee=()=>{
    const [values, setvalue]=  useState({id: " ", empname: " ", address:" ", gender: " ", date: " ", hobby: " " })
   const[employees, setemployees]= useState([])
  const handlechange =e=> {
     const name= e.target.name;
     const value= e.target.value;
      setvalue((prevState) => {
       return {...prevState, [name]: value}
        
    });
  };
  const employeepush =(e) =>{
    e.preventDefault();
    setemployees([...employees, values]);
    console.log(employees);
  }
return(
    <div>
        <label>Employee Id</label><input type="text" name="id" value={values.id} onChange={handlechange}></input>
        <label>Employee Name</label><input type="text" name="empname" value={values.empname} onChange={handlechange}></input>
        <label>Employee Address</label><input type="text" name="address" value={values.address} onChange={handlechange}></input>
        <input type="radio" id="male" name="gender" value="male"  {...values.gender} onChange={handlechange}></input>
      <label htmlFor="male">Male</label>
    <input type="radio" id="female" name="gender"  value=" female"{...values.gender} onChange={handlechange}></input>
    <label htmlFor="female">Female</label>
    <input type="radio" id="other" name="gender"  value= "other"{...values.gender} onChange={handlechange}></input>
    <label htmlFor="other">Other</label>
    <label>Date of Joining</label><input type="text" name="date"value={values.date} onChange={handlechange}></input>
    <label>Hobbies</label><input type="text" name="hobby" value={values.hobby} onChange={handlechange}></input>
    <button type="button" onClick={employeepush}>Submit</button>
    <table>
        <th>Id</th>
        <th>Name</th>
        <th>Address</th>
        <th>Gender</th>
        <th>Date of Joining</th>
        <th>Hobbies</th>
        {employees.map((emp)=>(
        <tr>
          <td>{emp.id}</td>
          <td>{emp.empname}</td>
          <td>{emp.address}</td>
          <td>{emp.gender}</td>
          <td>{emp.date}</td>
          <td>{emp.hobby}</td>
        </tr>
         ))}
    </table>
         </div>
)}
export default Employee

// Angular_React_Vue/Day4/Assignments/Angular/Source/assignment/src/app/employee/employee.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.css']
})
export class EmployeeComponent implements OnInit {
  
  constructor() { }
  employees:any=[]
  employee= {
    id: " "  ,
     name: " ",
    address: " ",
    gender: " ",
    date: " ",
    hobbies: " ",
  };
  ngOnInit(): void {
  }
check(){
var tempobj={empid:this.employee.id, empname: this.employee.name, empgender: this.employee.gender, empdate: this.employee.date, empaddress:this.employee.address, emphobby:this.employee.hobbies}
this.employees.push(tempobj);
console.log(this.employees);
this.employee.id=" ";
this.employee.name=" ";
this.employee.address=" ";
this.employee.date=" ";
this.employee.gender=" ";
this.employee.hobbies=" ";
}
}

<div class="w-75 mx-5 p-5">
    <h1 class=" m-2"> Employee Form</h1>
    <div class="d-block m-2 px-2">
    <label class="d-block">ID: </label><input type="text" [(ngModel)]="employee.id">
    </div>
    <div class="d-block m-2 px-2">
    <label class="d-block">Name: </label><input type="text" [(ngModel)]="employee.name">
    </div>
    <div class="m-2 px-2">
    <label class="d-block">Adress: </label><input type="text" [(ngModel)]="employee.address">
    </div>
    <div class="m-2 px-2">
    <input type="radio" id="male" name="gender" [(ngModel)]="employee.gender" value="male">
    <label for="male">Male</label><br>
    <input type="radio" id="female" name="gender" [(ngModel)]="employee.gender" value="female">
    <label for="female">Female</label><br>
    <input type="radio" id="other" name="gender" [(ngModel)]="employee.gender" value="other">
    <label for="other">Other</label>
    </div>
    <div class="m-2 px-2">
    <label class="d-block">Date of Joining</label><input type="text" [(ngModel)]="employee.date">
    </div>
    <div class="m-2 px-2">
    <label class="d-block">Hobbies</label><input type="text"[(ngModel)]="employee.hobbies">
    </div>
    <button type="button" (click)="check()" class="m-2">Submit</button>
    <table aria-label="table">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Gender</th>
            <th>Date of Joining</th>
            <th>Hobby</th>
        </thead>
        <tbody *ngFor="let item of employees">
            <tr>
                <td>{{item.empid}}</td>
                <td>{{item.empname}}</td>
                <td>{{item.empaddress}}</td>
                <td>{{item.empgender}}</td>
                <td>{{item.empdate}}</td>
                <td>{{item.emphobby}}</td>
            </tr>
        </tbody>
    </table>
</div>
