// Angular_React_Vue/Day7/Practice/React/Source/chidltoparent/src/ProFile.js
import react, {useState} from 'react';
export default function ProFile(props){
const [myname, setmyname]= useState('')
function display(){
    props.getdata(myname);
}
return (
    <div>
        <input type="text" onChange={(e)=>setmyname(e.target.value)}></input>
        <button type="button" onClick={display}>Display</button>
    </div>
)
}

// Angular_React_Vue/Day7/Practice/Vue/Source/childtoparent/src/components/ProFile.vue
<template lang="">
    <div>
      <label>Name</label>
<input type="text" v-model="myname">
<button type="button" @click="display()">Display</button>  
    </div>
</template>
<script>
export default {
    name: "ProFile",
    props:{
        message: String
    },
    data() {
        return {
            myname:'',
        }
    },
    methods: {
        display(){
             this.$emit('getData', this.myname);
        }
    },
}
</script>
<style lang="">
    
</style>
