// React/Day2/Assignments/SourceCode/assignment/src/Components/FooTer.js
import React from 'react';
export class FooTer extends React.Component{
        render(){
            return(
                <div id="footer">
                <p id="copyright"> 2022 copyright. DO NOT COPY OUR CONTENT!</p>
                </div>
            )

        }
   
}
export default FooTer;

// Angular_React_Vue/Day2/Assignments/Angular/Source/assignment/src/app/foo-ter/foo-ter.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-foo-ter',
  templateUrl: './foo-ter.component.html',
  styleUrls: ['./foo-ter.component.css']
})
export class FooTerComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div id="footer">
    <p> 2022 copyright. DO NOT COPY OUR CONTENT!</p>
    </div>
