// Angular_React_Vue/Day2/Assignments/Vue/Source/assignment/src/components/FooTer.vue
<template lang="">
    <div>
        <div id="footer">
            <p> 2022 copyright. DO NOT COPY OUR CONTENT!</p>
            </div>
    </div>
</template>
<script>
export default {
    name: "FooTer"
}
</script>
<style scoped>
    #footer{
        margin-bottom:0px;
        position:sticky;
        background-color: black;
        color: white;
        }
        p{
            color:white;
            }
</style>

// React/Day2/Assignments/SourceCode/assignment/src/Components/FooTer.js
import React from 'react';
export class FooTer extends React.Component{
        render(){
            return(
                <div id="footer">
                <p id="copyright"> 2022 copyright. DO NOT COPY OUR CONTENT!</p>
                </div>
            )

        }
   
}
export default FooTer;
