// Angular_React_Vue/Day2/Assignments/Angular/Source/assignment/src/app/section-home/section-home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-section-home',
  templateUrl: './section-home.component.html',
  styleUrls: ['./section-home.component.css']
})
export class SectionHomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div id="home">
    <div id="home-head">
    <h1>Home</h1>
</div>
<div id="home-body">
    <p>
        This is the home page of Resin with love. This will tell you about the origin and basic info of the brand.
    </p>
    <p>
        Resin with love originated as a brand that provides affordable resin handicrafts of best quality. It was established in 2021 in september, and has been running for over a six months now.
        The main goal of this brand is to provide the lowest rates of resin artifacts so that many people can use this. Resin is a trending chemical these days due to its glass like finish and durability.

        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa eveniet asperiores quas rerum eaque minus. Est at facilis eum optio laborum sunt maxime neque deleniti, minima, iste delectus quod aut.
    </p>
    <img src="../../assets/Images/WhatsApp Image 2022-02-08 at 23.31.52 (1).jpeg"  alt="image">
    <h2>Owners</h2>
    <p id="owners"> 
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum odio reiciendis a deserunt architecto minus quo. Quidem officia fugit delectus labore sunt libero ipsum asperiores quas repellat, nihil rerum veritatis!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora eum, esse reprehenderit fugiat aspernatur aut inventore? Labore corrupti itaque nostrum quasi similique vitae ducimus hic sapiente impedit, dicta saepe iste, alias architecto aliquid nobis quia eos? Repellat magni laboriosam doloribus tempora, rem ratione dignissimos in.
    Here are some links to the owner's socials as well the brands' socials:<br>
    </p>
    <a href="#">Resin with love</a><br>
    <a href="#">Resin with love</a><br>
    <a href="#">Resin with love</a><br>
</div>
</div>

// React/Day2/Assignments/SourceCode/assignment/src/Components/SectionHome.js
import React from 'react';
export class SectionHome extends React.Component{
        render(){
            return(
                <div id="home">
             <div id="home-head">
             <h1>Home</h1>
         </div>
         <div id="home-body">
             <p>
                 This is the home page of Resin with love. This will tell you about the origin and basic info of the brand.
             </p>
             <p>
                 Resin with love originated as a brand that provides affordable resin handicrafts of best quality. It was established in 2021 in september, and has been running for over a six months now.
                 The main goal of this brand is to provide the lowest rates of resin artifacts so that many people can use this. Resin is a trending chemical these days due to its glass like finish and durability.
         
                 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa eveniet asperiores quas rerum eaque minus. Est at facilis eum optio laborum sunt maxime neque deleniti, minima, iste delectus quod aut.
             </p>
             <h2>Owners</h2>
             <p id="owners"> 
                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum odio reiciendis a deserunt architecto minus quo. Quidem officia fugit delectus labore sunt libero ipsum asperiores quas repellat, nihil rerum veritatis!
                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora eum, esse reprehenderit fugiat aspernatur aut inventore? Labore corrupti itaque nostrum quasi similique vitae ducimus hic sapiente impedit, dicta saepe iste, alias architecto aliquid nobis quia eos? Repellat magni laboriosam doloribus tempora, rem ratione dignissimos in.
             Here are some links to the owner's socials as well the brands' socials:
             </p>
             <a href="#">Resin with love</a>
             <a href="#">Resin with love</a>
             <a href="#">Resin with love</a>
         </div>
         </div>
            )

        }
   
}
export default SectionHome;
